name: Release

# Controls when the action will run.
on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build-release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write release version
        run: |
          TAG=${{github.ref_name}}
          echo "VERSION=${TAG:1}" >> $GITHUB_ENV

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install clojure cli
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.2.1446

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Datalevin DB File
        run: clojure -X:extract

      - name: Debug artifacts
        run: ls -lah target/docs-db

      - name: Zips artifacts
        run: zip -r -j docs-db.zip target/docs-db/*

      - name: Release to GiHub
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
